import { describe, expect, it } from "vitest";

import {
  buildCategoryBreakdown,
  buildCoverageBreakdown,
  buildExpiryBreakdown,
  buildPantryReportHtml,
} from "@/features/home/lib/exportPantryReport";
import type { PantryStats, RecipeCoverage } from "@/features/home/lib/pantryStats";

const stats: PantryStats = {
  total: 18,
  freshCount: 13,
  freshPercent: 72,
  expiring48h: 3,
  expiringSoon: [],
  byCategory: [
    { category: "Produce", count: 6 },
    { category: "Dairy", count: 3 },
  ],
  expiryWindows: [
    { label: "today", count: 0 },
    { label: "oneTwo", count: 3 },
    { label: "threeSeven", count: 4 },
    { label: "eightPlus", count: 11 },
  ],
};

const coverage: RecipeCoverage = { ready: 2, oneAway: 4, other: 1 };

const labels = {
  title: "Pantry at a glance",
  totalItems: "Total items",
  fresh: "Fresh",
  expiring48h: "Expiring in 48h",
  expiryWindows: "Expiring soon",
  categories: "Category breakdown",
  recipeCoverage: "Recipe coverage",
  ready: "Ready",
  oneAway: "1 away",
  other: "Other",
  snapshotAt: "Pantry snapshot",
  lastUpdated: "Last updated",
  generatedBy: "Generated by",
  windowLabels: {
    today: "Today",
    oneTwo: "1–2d",
    threeSeven: "3–7d",
    eightPlus: "8+d",
  },
  expiryChartDesc: "Bar chart: Today: 0, 1–2d: 3",
  categoryChartDesc: "Categories across 18 items: Produce (6), Dairy (3)",
  coverageChartDesc: "Coverage: Ready: 2, 1 away: 4, Other: 1",
  attentionNote: "3 items need attention soon.",
};

describe("pantry report export helpers", () => {
  it("builds expiry breakdown text", () => {
    expect(buildExpiryBreakdown(stats, labels.windowLabels)).toBe(
      "Today: 0, 1–2d: 3, 3–7d: 4, 8+d: 11",
    );
  });

  it("builds category breakdown text", () => {
    expect(buildCategoryBreakdown(stats)).toBe("Produce (6), Dairy (3)");
  });

  it("builds coverage breakdown text", () => {
    expect(buildCoverageBreakdown(coverage, labels)).toBe("Ready: 2, 1 away: 4, Other: 1");
  });

  it("includes accessible chart descriptions in printable HTML", () => {
    const html = buildPantryReportHtml({
      stats,
      coverage,
      labels,
      timestamps: { snapshotAt: new Date("2026-06-28T10:00:00Z"), lastUpdated: null },
      locale: "en",
    });

    expect(html).toContain(labels.expiryChartDesc);
    expect(html).toContain(labels.categoryChartDesc);
    expect(html).toContain(labels.coverageChartDesc);
    expect(html).toContain("Pantry snapshot");
    expect(html).toContain("Last updated");
  });
});
